name = "tildas-tonies"
main = "index.js"
compatibility_date = "2023-12-27"
workers_dev = false
route = { pattern = "api.tildas-tonies.de", custom_domain = true }
kv_namespaces = [
  { binding = "kv", id = "__CLOUDFLARE_KV_ID__" }
]

[triggers]
crons = ["0 13 * * sat"] # To keep the access token fresh when no one is accessing the page.

[vars]
CORS_ORIGINS = "https://tildas-tonies.de"