name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Replace IDs in wrangler.toml
        uses: falnyr/replace-env-vars-action@master
        env:
          CLOUDFLARE_KV_ID: ${{ secrets.CLOUDFLARE_KV_ID }}
        with:
          filename: ./workers/wrangler.toml
      - name: Deploy backend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy
          workingDirectory: workers
      - name: Deploy frontend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy pages --project-name=tildas-tonies